In [29]:
%pip install qiskit
%pip install qiskit_aer
%pip install qiskit_machine_learning

%pip install matplotlib
%pip install pylatexenc

%pip install tensorflow
%pip install keras

%pip install --upgrade openpyxl
%pip install pandas

%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [30]:
import pandas as pd
df = pd.read_csv("C:/Users/HP\Downloads/statlog+german+credit+data/german.data", sep=' ',
                 names=["AccountStatus", "Duration", "CreditHistory", "Purpose",
                        "CreditAmount", "AccountType", "EmploymentSince", "InstallmentRate",
                        "MaritalStatus", "IsDebtors", "ResidenceSince", "Property",
                        "Age", "InstallmentPlans", "Housing", "NumberOfCredits",
                        "Occupation", "NumberOfPeopleLiable", "IsTelephone", "IsForeignWorker",
                        "Class"])
df

AccountStatus  Duration CreditHistory Purpose  CreditAmount AccountType  \
0             A11         6           A34     A43          1169         A65   
1             A12        48           A32     A43          5951         A61   
2             A14        12           A34     A46          2096         A61   
3             A11        42           A32     A42          7882         A61   
4             A11        24           A33     A40          4870         A61   
..            ...       ...           ...     ...           ...         ...   
995           A14        12           A32     A42          1736         A61   
996           A11        30           A32     A41          3857         A61   
997           A14        12           A32     A43           804         A61   
998           A11        45           A32     A43          1845         A61   
999           A12        45           A34     A41          4576         A62   

    EmploymentSince  InstallmentRate MaritalStatus IsDebtors  ...  Property  \
0               A75                4           A93      A101  ...      A121   
1               A73                2           A92      A101  ...      A121   
2               A74                2           A93      A101  ...      A121   
3               A74                2           A93      A103  ...      A122   
4               A73                3           A93      A101  ...      A124   
..              ...              ...           ...       ...  ...       ...   
995             A74                3           A92      A101  ...      A121   
996             A73                4           A91      A101  ...      A122   
997             A75                4           A93      A101  ...      A123   
998             A73                4           A93      A101  ...      A124   
999             A71                3           A93      A101  ...      A123   

    Age  InstallmentPlans Housing NumberOfCredits  Occupation  \
0    67              A143    A152               2        A173   
1    22              A143    A152               1        A173   
2    49              A143    A152               1        A172   
3    45              A143    A153               1        A173   
4    53              A143    A153               2        A173   
..   ..               ...     ...             ...         ...   
995  31              A143    A152               1        A172   
996  40              A143    A152               1        A174   
997  38              A143    A152               1        A173   
998  23              A143    A153               1        A173   
999  27              A143    A152               1        A173   

    NumberOfPeopleLiable  IsTelephone IsForeignWorker Class  
0                      1         A192            A201     1  
1                      1         A191            A201     2  
2                      2         A191            A201     1  
3                      2         A191            A201     1  
4                      2         A191            A201     2  
..                   ...          ...             ...   ...  
995                    1         A191            A201     1  
996                    1         A192            A201     1  
997                    1         A191            A201     1  
998                    1         A192            A201     2  
999                    1         A191            A201     1  

[1000 rows x 21 columns]

In [31]:
numerical_cols = ['Duration', 'CreditAmount', 'InstallmentRate', 'ResidenceSince', 'Age', 'NumberOfCredits', 'NumberOfPeopleLiable']
categorical_cols = ['AccountStatus', 'CreditHistory', 'Purpose', 'AccountType', 'EmploymentSince', 'MaritalStatus',
                    'IsDebtors', 'Property', 'InstallmentPlans', 'Housing', 'Occupation', 'IsTelephone', 'IsForeignWorker']
classification_col = 'Class'


In [32]:
df[classification_col].replace([1,2], [1,0], inplace=True)
df[classification_col].value_counts()

C:\Users\HP\AppData\Local\Temp\ipykernel_4172\4201975059.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[classification_col].replace([1,2], [1,0], inplace=True)


Class
1    700
0    300
Name: count, dtype: int64

In [33]:
df

AccountStatus  Duration CreditHistory Purpose  CreditAmount AccountType  \
0             A11         6           A34     A43          1169         A65   
1             A12        48           A32     A43          5951         A61   
2             A14        12           A34     A46          2096         A61   
3             A11        42           A32     A42          7882         A61   
4             A11        24           A33     A40          4870         A61   
..            ...       ...           ...     ...           ...         ...   
995           A14        12           A32     A42          1736         A61   
996           A11        30           A32     A41          3857         A61   
997           A14        12           A32     A43           804         A61   
998           A11        45           A32     A43          1845         A61   
999           A12        45           A34     A41          4576         A62   

    EmploymentSince  InstallmentRate MaritalStatus IsDebtors  ...  Property  \
0               A75                4           A93      A101  ...      A121   
1               A73                2           A92      A101  ...      A121   
2               A74                2           A93      A101  ...      A121   
3               A74                2           A93      A103  ...      A122   
4               A73                3           A93      A101  ...      A124   
..              ...              ...           ...       ...  ...       ...   
995             A74                3           A92      A101  ...      A121   
996             A73                4           A91      A101  ...      A122   
997             A75                4           A93      A101  ...      A123   
998             A73                4           A93      A101  ...      A124   
999             A71                3           A93      A101  ...      A123   

    Age  InstallmentPlans Housing NumberOfCredits  Occupation  \
0    67              A143    A152               2        A173   
1    22              A143    A152               1        A173   
2    49              A143    A152               1        A172   
3    45              A143    A153               1        A173   
4    53              A143    A153               2        A173   
..   ..               ...     ...             ...         ...   
995  31              A143    A152               1        A172   
996  40              A143    A152               1        A174   
997  38              A143    A152               1        A173   
998  23              A143    A153               1        A173   
999  27              A143    A152               1        A173   

    NumberOfPeopleLiable  IsTelephone IsForeignWorker Class  
0                      1         A192            A201     1  
1                      1         A191            A201     0  
2                      2         A191            A201     1  
3                      2         A191            A201     1  
4                      2         A191            A201     0  
..                   ...          ...             ...   ...  
995                    1         A191            A201     1  
996                    1         A192            A201     1  
997                    1         A191            A201     1  
998                    1         A192            A201     0  
999                    1         A191            A201     1  

[1000 rows x 21 columns]

In [34]:
for col_name in df[categorical_cols]:
    if(df[col_name].dtype == 'object'):
        df[col_name]= df[col_name].astype('category')
        df[col_name] = df[col_name].cat.codes

df

AccountStatus  Duration  CreditHistory  Purpose  CreditAmount  \
0                0         6              4        4          1169   
1                1        48              2        4          5951   
2                3        12              4        7          2096   
3                0        42              2        3          7882   
4                0        24              3        0          4870   
..             ...       ...            ...      ...           ...   
995              3        12              2        3          1736   
996              0        30              2        1          3857   
997              3        12              2        4           804   
998              0        45              2        4          1845   
999              1        45              4        1          4576   

     AccountType  EmploymentSince  InstallmentRate  MaritalStatus  IsDebtors  \
0              4                4                4              2          0   
1              0                2                2              1          0   
2              0                3                2              2          0   
3              0                3                2              2          2   
4              0                2                3              2          0   
..           ...              ...              ...            ...        ...   
995            0                3                3              1          0   
996            0                2                4              0          0   
997            0                4                4              2          0   
998            0                2                4              2          0   
999            1                0                3              2          0   

     ...  Property  Age  InstallmentPlans  Housing  NumberOfCredits  \
0    ...         0   67                 2        1                2   
1    ...         0   22                 2        1                1   
2    ...         0   49                 2        1                1   
3    ...         1   45                 2        2                1   
4    ...         3   53                 2        2                2   
..   ...       ...  ...               ...      ...              ...   
995  ...         0   31                 2        1                1   
996  ...         1   40                 2        1                1   
997  ...         2   38                 2        1                1   
998  ...         3   23                 2        2                1   
999  ...         2   27                 2        1                1   

     Occupation  NumberOfPeopleLiable  IsTelephone  IsForeignWorker  Class  
0             2                     1            1                0      1  
1             2                     1            0                0      0  
2             1                     2            0                0      1  
3             2                     2            0                0      1  
4             2                     2            0                0      0  
..          ...                   ...          ...              ...    ...  
995           1                     1            0                0      1  
996           3                     1            1                0      1  
997           2                     1            0                0      1  
998           2                     1            1                0      0  
999           2                     1            0                0      1  

[1000 rows x 21 columns]

In [35]:
for col_name in df[categorical_cols]:
  df[col_name] = pd.to_numeric(df[col_name])

df

AccountStatus  Duration  CreditHistory  Purpose  CreditAmount  \
0                0         6              4        4          1169   
1                1        48              2        4          5951   
2                3        12              4        7          2096   
3                0        42              2        3          7882   
4                0        24              3        0          4870   
..             ...       ...            ...      ...           ...   
995              3        12              2        3          1736   
996              0        30              2        1          3857   
997              3        12              2        4           804   
998              0        45              2        4          1845   
999              1        45              4        1          4576   

     AccountType  EmploymentSince  InstallmentRate  MaritalStatus  IsDebtors  \
0              4                4                4              2          0   
1              0                2                2              1          0   
2              0                3                2              2          0   
3              0                3                2              2          2   
4              0                2                3              2          0   
..           ...              ...              ...            ...        ...   
995            0                3                3              1          0   
996            0                2                4              0          0   
997            0                4                4              2          0   
998            0                2                4              2          0   
999            1                0                3              2          0   

     ...  Property  Age  InstallmentPlans  Housing  NumberOfCredits  \
0    ...         0   67                 2        1                2   
1    ...         0   22                 2        1                1   
2    ...         0   49                 2        1                1   
3    ...         1   45                 2        2                1   
4    ...         3   53                 2        2                2   
..   ...       ...  ...               ...      ...              ...   
995  ...         0   31                 2        1                1   
996  ...         1   40                 2        1                1   
997  ...         2   38                 2        1                1   
998  ...         3   23                 2        2                1   
999  ...         2   27                 2        1                1   

     Occupation  NumberOfPeopleLiable  IsTelephone  IsForeignWorker  Class  
0             2                     1            1                0      1  
1             2                     1            0                0      0  
2             1                     2            0                0      1  
3             2                     2            0                0      1  
4             2                     2            0                0      0  
..          ...                   ...          ...              ...    ...  
995           1                     1            0                0      1  
996           3                     1            1                0      1  
997           2                     1            0                0      1  
998           2                     1            1                0      0  
999           2                     1            0                0      1  

[1000 rows x 21 columns]

In [36]:
numerical_cols = ['Duration', 'CreditAmount', 'InstallmentRate', 'ResidenceSince', 'Age', 'NumberOfCredits', 'NumberOfPeopleLiable']

In [37]:
from sklearn.preprocessing import StandardScaler

df_numerical_cols = pd.DataFrame(StandardScaler().fit_transform(df[numerical_cols]))
df_numerical_cols

0         1         2         3         4         5         6
0   -1.236478 -0.745131  0.918477  1.046987  2.766456  1.027079 -0.428290
1    2.248194  0.949817 -0.870183 -0.765977 -1.191404 -0.704926 -0.428290
2   -0.738668 -0.416562 -0.870183  0.140505  1.183312 -0.704926  2.334869
3    1.750384  1.634247 -0.870183  1.046987  0.831502 -0.704926  2.334869
4    0.256953  0.566664  0.024147  1.046987  1.535122  1.027079  2.334869
..        ...       ...       ...       ...       ...       ...       ...
995 -0.738668 -0.544162  0.024147  1.046987 -0.399832 -0.704926 -0.428290
996  0.754763  0.207612  0.918477  1.046987  0.391740 -0.704926 -0.428290
997 -0.738668 -0.874503  0.918477  1.046987  0.215835 -0.704926 -0.428290
998  1.999289 -0.505528  0.918477  1.046987 -1.103451 -0.704926 -0.428290
999  1.999289  0.462457  0.024147  1.046987 -0.751642 -0.704926 -0.428290

[1000 rows x 7 columns]

In [38]:
df = df.drop(numerical_cols, axis = 1)
df = pd.concat([df_numerical_cols, df], axis = 1)
df

0         1         2         3         4         5         6  \
0   -1.236478 -0.745131  0.918477  1.046987  2.766456  1.027079 -0.428290   
1    2.248194  0.949817 -0.870183 -0.765977 -1.191404 -0.704926 -0.428290   
2   -0.738668 -0.416562 -0.870183  0.140505  1.183312 -0.704926  2.334869   
3    1.750384  1.634247 -0.870183  1.046987  0.831502 -0.704926  2.334869   
4    0.256953  0.566664  0.024147  1.046987  1.535122  1.027079  2.334869   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.738668 -0.544162  0.024147  1.046987 -0.399832 -0.704926 -0.428290   
996  0.754763  0.207612  0.918477  1.046987  0.391740 -0.704926 -0.428290   
997 -0.738668 -0.874503  0.918477  1.046987  0.215835 -0.704926 -0.428290   
998  1.999289 -0.505528  0.918477  1.046987 -1.103451 -0.704926 -0.428290   
999  1.999289  0.462457  0.024147  1.046987 -0.751642 -0.704926 -0.428290   

     AccountStatus  CreditHistory  Purpose  ...  EmploymentSince  \
0                0              4        4  ...                4   
1                1              2        4  ...                2   
2                3              4        7  ...                3   
3                0              2        3  ...                3   
4                0              3        0  ...                2   
..             ...            ...      ...  ...              ...   
995              3              2        3  ...                3   
996              0              2        1  ...                2   
997              3              2        4  ...                4   
998              0              2        4  ...                2   
999              1              4        1  ...                0   

     MaritalStatus  IsDebtors  Property  InstallmentPlans  Housing  \
0                2          0         0                 2        1   
1                1          0         0                 2        1   
2                2          0         0                 2        1   
3                2          2         1                 2        2   
4                2          0         3                 2        2   
..             ...        ...       ...               ...      ...   
995              1          0         0                 2        1   
996              0          0         1                 2        1   
997              2          0         2                 2        1   
998              2          0         3                 2        2   
999              2          0         2                 2        1   

     Occupation  IsTelephone  IsForeignWorker  Class  
0             2            1                0      1  
1             2            0                0      0  
2             1            0                0      1  
3             2            0                0      1  
4             2            0                0      0  
..          ...          ...              ...    ...  
995           1            0                0      1  
996           3            1                0      1  
997           2            0                0      1  
998           2            1                0      0  
999           2            0                0      1  

[1000 rows x 21 columns]

In [39]:
X = df.drop('Class', axis=1)
y = pd.DataFrame(df['Class'])


In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=None, shuffle=True, stratify=y)

print(y_train.value_counts())
print(y_test.value_counts())

Class
1        560
0        240
Name: count, dtype: int64
Class
1        140
0         60
Name: count, dtype: int64


In [41]:
X_train.shape

(800, 20)

In [42]:
X_train.iloc[0]

0                  -0.738668
1                  -0.802551
2                   0.918477
3                  -1.672459
4                  -1.191404
5                  -0.704926
6                  -0.428290
AccountStatus       1.000000
CreditHistory       2.000000
Purpose             0.000000
AccountType         3.000000
EmploymentSince     2.000000
MaritalStatus       3.000000
IsDebtors           0.000000
Property            0.000000
InstallmentPlans    2.000000
Housing             1.000000
Occupation          2.000000
IsTelephone         0.000000
IsForeignWorker     0.000000
Name: 67, dtype: float64

In [43]:
X_train[:1]

0         1         2         3         4         5        6  \
67 -0.738668 -0.802551  0.918477 -1.672459 -1.191404 -0.704926 -0.42829   

    AccountStatus  CreditHistory  Purpose  AccountType  EmploymentSince  \
67              1              2        0            3                2   

    MaritalStatus  IsDebtors  Property  InstallmentPlans  Housing  Occupation  \
67              3          0         0                 2        1           2   

    IsTelephone  IsForeignWorker  
67            0                0

In [44]:
from qiskit import QuantumCircuit
from qiskit_aer import Aer
from qiskit import transpile
from qiskit.circuit.library import ZZFeatureMap

import numpy as np

In [45]:
n_qubits = 20

In [46]:
qc = QuantumCircuit(n_qubits)

feature_map = ZZFeatureMap(feature_dimension=n_qubits, entanglement="full", reps=2)
qc.append(feature_map, range(n_qubits))

for i in range(n_qubits):
  qc.rx(np.random.uniform(0, 2 * np.pi), i)
  qc.rz(np.random.uniform(0, 2 * np.pi), i)
  qc.cx(i, (i + 1) % n_qubits)

#qc.measure_all()

qc.draw()

»
 q_0: »
      »
 q_1: »
      »
 q_2: »
      »
 q_3: »
      »
 q_4: »
      »
 q_5: »
      »
 q_6: »
      »
 q_7: »
      »
 q_8: »
      »
 q_9: »
      »
q_10: »
      »
q_11: »
      »
q_12: »
      »
q_13: »
      »
q_14: »
      »
q_15: »
      »
q_16: »
      »
q_17: »
      »
q_18: »
      »
q_19: »
      »
«      ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐»
« q_0: ┤0                                                                                                                              ├»
«      │                                                                                                                               │»
« q_1: ┤1                                                                                                                              ├»
«      │                                                                                                                               │»
« q_2: ┤2                                                                                                                              ├»
«      │                                                                                                                               │»
« q_3: ┤3                                                                                                                              ├»
«      │                                                                                                                               │»
« q_4: ┤4                                                                                                                              ├»
«      │                                                                                                                               │»
« q_5: ┤5                                                                                                                              ├»
«      │                                                                                                                               │»
« q_6: ┤6                                                                                                                              ├»
«      │                                                                                                                               │»
« q_7: ┤7                                                                                                                              ├»
«      │                                                                                                                               │»
« q_8: ┤8                                                                                                                              ├»
«      │                                                                                                                               │»
« q_9: ┤9                                                                                                                              ├»
«      │   ZZFeatureMap(x[0],x[1],x[2],x[3],x[4],x[5],x[6],x[7],x[8],x[9],x[10],x[11],x[12],x[13],x[14],x[15],x[16],x[17],x[18],x[19]) │»
«q_10: ┤10                                                                                                                             ├»
«      │                                                                                                                               │»
«q_11: ┤11                                                                                                                             ├»
«      │                                                                                                                               │»
«q_12: ┤12                                                                                                                             ├»
«      │                                                                                  

In [47]:
print(qc.num_parameters)

20


In [48]:
print(qc.parameters)

ParameterView([ParameterVectorElement(x[0]), ParameterVectorElement(x[1]), ParameterVectorElement(x[2]), ParameterVectorElement(x[3]), ParameterVectorElement(x[4]), ParameterVectorElement(x[5]), ParameterVectorElement(x[6]), ParameterVectorElement(x[7]), ParameterVectorElement(x[8]), ParameterVectorElement(x[9]), ParameterVectorElement(x[10]), ParameterVectorElement(x[11]), ParameterVectorElement(x[12]), ParameterVectorElement(x[13]), ParameterVectorElement(x[14]), ParameterVectorElement(x[15]), ParameterVectorElement(x[16]), ParameterVectorElement(x[17]), ParameterVectorElement(x[18]), ParameterVectorElement(x[19])])


In [49]:
n_shots = 1024

backend = Aer.get_backend('statevector_simulator')

In [50]:
train_outputs = []
for i in range(len(X_train)):
  compiled_circuit = transpile(qc, backend)
  compiled_circuit = compiled_circuit.assign_parameters(X_train.iloc[i])

  result = backend.run(compiled_circuit, shots=n_shots).result()
  statevector = result.get_statevector()

  train_outputs.append(np.abs(statevector)**2)

train_outputs

[array([2.47732368e-07, 6.17403305e-08, 7.98004317e-08, ...,
        1.96964314e-07, 9.11742104e-08, 2.80432721e-07]),
 array([6.69002879e-06, 6.15617879e-06, 1.29258806e-06, ...,
        9.33035529e-07, 8.72908058e-06, 5.62545109e-06]),
 array([2.39700908e-06, 2.66552127e-07, 6.43913036e-08, ...,
        1.39364071e-06, 3.20763918e-07, 6.87358606e-07]),
 array([4.97446269e-07, 2.52077263e-07, 3.43599031e-08, ...,
        5.23714005e-07, 5.47443604e-08, 1.67725138e-07]),
 array([2.82400616e-06, 2.41800867e-06, 7.03953647e-07, ...,
        4.39727440e-06, 8.92952344e-06, 1.25698691e-06]),
 array([2.12418371e-06, 3.07805671e-06, 5.18673314e-06, ...,
        1.72224238e-07, 1.54004663e-05, 1.42542215e-07]),
 array([4.86839039e-07, 4.61638735e-08, 2.50549019e-07, ...,
        1.93991549e-07, 1.59355368e-06, 8.30031144e-07]),
 array([1.38961747e-06, 2.06564182e-06, 4.78458371e-07, ...,
        8.11316780e-07, 1.17853298e-06, 4.89502100e-07]),
 array([5.43220287e-07, 7.65769665e-07, 2.800862

In [51]:
len(train_outputs)

800

In [52]:
len(y_train)

800

In [53]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(max_iter=1000)
classifier.fit(train_outputs, y_train)

c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(max_iter=1000)

In [54]:
test_outputs = []
for i in range(len(X_test)):
  compiled_circuit = transpile(qc, backend)
  compiled_circuit = compiled_circuit.assign_parameters(X_test.iloc[i])

  result = backend.run(compiled_circuit, shots=n_shots).result()
  statevector = result.get_statevector()
  
  test_outputs.append(np.abs(statevector)**2)

test_outputs

[array([1.00253288e-06, 4.67852707e-07, 3.78258348e-07, ...,
        7.75180634e-07, 2.60072072e-07, 3.77197411e-07]),
 array([6.04344142e-07, 4.24969615e-08, 3.83029713e-06, ...,
        2.58708108e-06, 2.69451131e-07, 5.70728622e-07]),
 array([1.00561839e-07, 1.03412476e-07, 8.71558327e-08, ...,
        5.12847531e-09, 4.05857338e-07, 8.05463000e-07]),
 array([1.69248362e-06, 1.94978004e-06, 9.92479893e-08, ...,
        2.85304377e-07, 6.95670919e-08, 2.19314355e-07]),
 array([4.10223400e-07, 8.47618180e-07, 8.48642468e-08, ...,
        1.83237521e-07, 6.07896797e-07, 2.77497511e-08]),
 array([7.37265457e-07, 9.88617293e-07, 1.30822769e-07, ...,
        1.00239032e-06, 1.02587555e-07, 1.60453768e-06]),
 array([2.71810380e-07, 2.30990289e-07, 9.39902067e-07, ...,
        1.87768419e-07, 5.45453970e-08, 1.68992386e-08]),
 array([9.73229530e-07, 3.65563295e-07, 8.50200385e-07, ...,
        3.71911443e-07, 5.39373827e-07, 6.27984787e-07]),
 array([1.52168523e-08, 1.99147687e-08, 3.066367

In [55]:
y_pred = classifier.predict(test_outputs)

In [56]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix, roc_curve, auc

print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))
print(f'Accuracy Score: {accuracy_score(y_test, y_pred)}')
print(f'Precision Score: {precision_score(y_test, y_pred, average="macro")}')
print(f'Recall Score: {recall_score(y_test, y_pred, average="macro")}')
print(f'F1 Score: {f1_score(y_test, y_pred, average="macro")}')
fpr, tpr, thresholds = roc_curve(y_test, y_pred)
roc_auc = auc(fpr, tpr)
print(f'ROC AUC: {roc_auc}')

Confusion Matrix:
[[  0  60]
 [  0 140]]
Accuracy Score: 0.7
Precision Score: 0.35
Recall Score: 0.5
F1 Score: 0.4117647058823529
ROC AUC: 0.5


c:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
